### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by mrWONDERFULguy** [Vahera/godot-orchestrator#100]
### Describe the bug

I downloaded 2.0 but it is not showing up in the editor. 
![Uploading Screenshot 2024-02-20 at 7.57.23 PM.jpg…]()

**Comment by mrWONDERFULguy** [comment]
Hello and thanks.  I grabbed the 2.0 version   I.created a new project and put the folder in the file root.  Saved it and restarted.  But it didn’t show up. I also tried to download  it directly fro, the asset manager. And that didn’t work either. I am, using godot 4.2 and on a Mac Studio. Thank u. I am excited to try your plugin. Sent from my iPadOn Feb 20, 2024, at 9:47 PM, Chris Cranford ***@***.***> wrote:﻿
Hi @mrWONDERFULguy, can you describe the steps you took to install the add-on?  Also what version of the Godot Editor are you using?  Unfortunately your screen shot was not saved and cannot be viewed.

**Comment by Naros** [comment]
The version in the Asset Library is still version 1, I would not recommend using that one any longer.  

I suggest getting the build I added to this Github issue:
https://github.com/Vahera/godot-orchestrator/issues/82#issuecomment-1909000205

That build fixes a crash.  After replacing the `addons/orchestrator` folder contents with the zip in the above link, if it still does not show up after restarting the editor, then I would suggest looking in the output panel of the editor and share any information that Godot prints there @mrWONDERFULguy .

**Comment by mrWONDERFULguy** [comment]
Ok. I will try and give you an update. Thanks for your assistance.  https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 20, 2024, at 10:18 PM, Chris Cranford ***@***.***> wrote:﻿
The version in the Asset Library is still version 1, I would not recommend using that one any longer.
I suggest getting the build I added to this Github issue:
#82 (comment)
That build fixes a crash.  After replacing the addons/orchestrator folder contents with the zip in the above link, if it still does not show up after restarting the editor, then I would suggest looking in the output panel of the editor and share any information that Godot prints there @mrWONDERFULguy .

**Comment by mrWONDERFULguy** [comment]
Hello, I’m a noob to Godot so I’m most likely doing something wrong.  Do I place the addon in a  Godot plugin folder?   https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 20, 2024, at 10:39 PM, Eric Rosner ***@***.***> wrote:﻿Ok. I will try and give you an update. Thanks for your assistance.  https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 20, 2024, at 10:18 PM, Chris Cranford ***@***.***> wrote:﻿
The version in the Asset Library is still version 1, I would not recommend using that one any longer.
I suggest getting the build I added to this Github issue:
#82 (comment)
That build fixes a crash.  After replacing the addons/orchestrator folder contents with the zip in the above link, if it still does not show up after restarting the editor, then I would suggest looking in the output panel of the editor and share any information that Godot prints there @mrWONDERFULguy .

**Comment by Naros** [comment]
Hi @mrWONDERFULguy so the zip file should already have the right folder structure, so you should just have to unzip it into your project directory so that Orchestrator exists in the `<project_root>\addons\orchestrator` directory.  This directory should content contents similar to this screen shot:

![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/cd100461-0f3f-409a-b49c-31e4e22235a8)

**Comment by Naros** [comment]
Did you get this solved @mrWONDERFULguy ?

**Comment by mrWONDERFULguy** [comment]
Hello. I got the 1.1 to install but I then tried to install the 2.0 alpha but it wouldn’t update.  I downloaded it from Git.  I’m also a godot noob so I might be doing it wrong.  I do hope you create some videos to show how to use it.  It seems amazing.  This is your unity bolt moment. Thank you.  https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 26, 2024, at 9:01 AM, Chris Cranford ***@***.***> wrote:﻿
Did you get this solved @mrWONDERFULguy ?

**Comment by Naros** [comment]
Hi @mrWONDERFULguy, please see the installation guide:
https://www.vahera.com/docs/orchestrator/2.0.0/installation-guide.html#_download_plugin

Let me know if you have any trouble, the 2.0.dev3 build was released just yesterday so the above steps should be all you need.

**Comment by mrWONDERFULguy** [comment]
Is this correct?

I don’t see the Orchestrator button 

￼


No button
￼

**Comment by mrWONDERFULguy** [comment]
Hmm its still not loading… I

Please me know what I am doing wrong 
￼



￼

**Comment by Mrdoumhann** [comment]
Hi, I also failed to get it to work.
I tried on M3 Mac with macos.universal v2.0-dev3 build
Here is the error output:
 
 Can't open dynamic library: /Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib. Error:dlopen(/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib, 0x0002): tried: '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS//Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (no such file), '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')).

  core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: //Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib
  Failed loading resource: res://addons/orchestrator/orchestrator.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by mrWONDERFULguy** [comment]
Oh no. So are Mac users sol? https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 26, 2024, at 8:17 PM, Mrdoumhann ***@***.***> wrote:﻿
Hi, I also failed to get it to work.
I tried on M3 Mac with macos.universal v2.0-dev3 build
Here is the error output:
Can't open dynamic library: /Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib. Error:dlopen(/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib, 0x0002): tried: '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS//Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (no such file), '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')).
core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: //Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib
Failed loading resource: res://addons/orchestrator/orchestrator.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by Naros** [comment]
> Can't open dynamic library: /Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib. Error:dlopen(/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib, 0x0002): tried: '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS//Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (no such file), '/Users/ed/Documents/Test/addons/orchestrator/orchestrator.darwin.64.release.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')).

The MacOS build should work, but I'll double-check.  Unfortunately, the only access to MacOS we have is on the GH action server where we build the source, so if I post some artifacts here to test, would you be able to verify if they work @Mrdoumhann ?

**Comment by NullMember** [comment]
MacOS dylib architecture from dev release is x86_64 and arm64 version of godot could not load the library. I've recompiled orchestrator from source and now it works on my M1 machine. Here is the orchestrator dylib for arm64 for testing.
[orchestrator.darwin.64.release.dylib.zip](https://github.com/Vahera/godot-orchestrator/files/14424360/orchestrator.darwin.64.release.dylib.zip)

Simply replace this file with <project>/addons/orchestrator/orchestrator.darwin.64.release.dylib

**Comment by Naros** [comment]
Hi @NullMember,  could you please open a PR with the changes needed to cmake?

**Comment by mrWONDERFULguy** [comment]
Hey you are featured on Games from scratch.   Is there a way to get it to work on a Mac??  Please help. Thanks.  https://www.erosner.com   917-405-8961  Demo reel
https://youtu.be/6pXxUzWEgwAOn Feb 27, 2024, at 3:35 PM, Chris Cranford ***@***.***> wrote:﻿
Hi @NullMember,  could you please open a PR with the changes needed to cmake?

**Comment by Naros** [comment]
HI @Mrdoumhann, see the MacOS a link above in the GitHub issue, NullMember added a custom build.  He also contributed a build change and I will be updating the `2.0.dev3` build later tonight.

**Comment by Naros** [comment]
@mrWONDERFULguy, updated the `dev3` build to include the MacOS fixes, see:
https://github.com/Vahera/godot-orchestrator/releases/tag/v2.0.dev3

**Comment by Mrdoumhann** [comment]
> HI @Mrdoumhann, see the MacOS a link above in the GitHub issue, NullMember added a custom build. He also contributed a build change and I will be updating the `2.0.dev3` build later tonight.

Hi, I just tried it and the problem seems to be solved.

**Comment by mrWONDERFULguy** [comment]
Hey, it works!!!  Exciting….  Not to be a pain but some videos on how to use it would be cool but thanks. !!! exiting

**Comment by Naros** [comment]
This video was made just today, check it out.
https://www.youtube.com/watch?v=Y53M53RYa_0
