### ISSUE TITLE
editor crashing when a new 'block' is created with bool conection

### ISSUE THREAD

**Issue by Pistolk1** [Vahera/godot-orchestrator#101]
### Describe the bug

whenever i drag a bool output for a 'block' the whole editor crashes, this is on the orchestrator v2dev2 build for the plugin

### Expected behavior

it would be expected that a menu would popup asking me what 'block' i would like to create next

### Actual behavior

the editor crashes

### How to Reproduce?

to reproduce this: 

1. create an inisial input event 'block'
2. configure the event input 'block' (optional)
3. drag the bool output and let go

### Godot full version

gd editor 4.2.1 stable winX86

### Orchestrator version

2.0 dev2

**Comment by Naros** [comment]
Hi @Pistolk1 please grab the build from this issue - https://github.com/Vahera/godot-orchestrator/issues/82#issuecomment-1909000205

We'll be doing a dev3 build later this weekend which will include this fix.

**Comment by Naros** [comment]
Closing as this should be baked into the new https://github.com/Vahera/godot-orchestrator/releases/tag/v2.0.dev3 release.
