### ISSUE TITLE
Possible to license the same as rustlang where we can choose MIT or Apache 2?

### ISSUE THREAD

**Issue by fire** [Vahera/godot-orchestrator#108]
### Description

Is it possible to license godot-orchestrator the same as rustlang where we can choose MIT or Apache 2?

### Implementation ideas

Was curious so that if we do want to merge into core it's possible.

**Comment by Naros** [comment]
> Was curious so that if we do want to merge into core it's possible.

Hi @fire, when you say "core", are you explicitly referring to merging this work under Godot's main repository?

**Comment by fire** [comment]
Well I'm not sure if it's something this year, but maybe something in the far far future. 

https://github.com/godotengine/godot/blob/master/LICENSE.txt

**Comment by Zomphie** [comment]
Hi Fire. At this time we are not looking to duel licensed Orchestrator.
