### ISSUE TITLE
can't add constants, etc

### ISSUE THREAD

**Issue by charlesmlamb** [Vahera/godot-orchestrator#115]
### Describe the bug

there's stuff missing

![image](https://github.com/Vahera/godot-orchestrator/assets/83387915/8587fafb-f530-4863-a416-fb0520112b69)

### Expected behavior

there should be constants, etc

### Actual behavior

there's a list not there, to add constants, etc

### Godot full version

Godot 4.2.1

### Orchestrator version

2.0.3 dev

**Comment by Naros** [comment]
If you right click on the graph canvas and search for constant, do you not see the following?

![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/4b12feca-b39e-494d-9488-c1562d8a7929)

**Comment by Naros** [comment]
Hi @charlesmlamb did the above solve your issue?  Can we close this if so?

**Comment by Naros** [comment]
Please feel free to re-open if there is an issue.

**Comment by charlesmlamb** [comment]
right - click not work, or etc
