### ISSUE TITLE
Support resource creation?

### ISSUE THREAD

**Issue by nullism** [Vahera/godot-orchestrator#117]
### Description

Hello! 

I installed this because I misunderstood what "Resource" meant in supported features. 

I was hoping I could have my own resources and graph them, for example:

```
[resource:Weapon]
hitEffects: Array[HitEffect]

[resource:HitEffect]
damage: int
```

Then I could create a resource and graph the properties, saving the orchestration as a the resource.

In this example I'd add a "new Weapon" and a few "new HitEffect" and draw lines from the Weapon to the effects. 

Another example of this is custom dialog resources.

Is this something we'd see supported or is this out of scope for this project?

**Comment by Naros** [comment]
So Orchestrator isn't designed to create resources in this context, it's designed to create game logic much in the same context as you would use GDScript or C# to create functions and callbacks to handle specific game events.  

But I do think what you're describing aligns quite well with the discussion in #94, which is something we want to consider in the future.  Take a look at that issue and let me know if you think that sounds similar or would work for you.

As for custom dialog resources, can you elaborate more on this?  My initial take on how you mention this seems to align closely with the 2D viewport and `.tscn` files for UI, but maybe I am misunderstanding you.

**Comment by Naros** [comment]
I am assuming by `ResourceGraph` in this context of your original post, you're wanting to be able to compose resources without having to use GDScript like this:

```
class_name Weapon
extends Resource

@export var hitEffects : Array[HitEffect]
```

**Comment by nullism** [comment]
Oh I understand what you mean. No that's not what I meant, but I think that'd make sense for this tool. 

So my suggestion of `ResourceGraph` is a bad name. I just want to be able to visualize my existing resources with sub resources. Like I want to see all the damage hit effects graphed for a given item rather than using the inspector (which is hard to use given a certain level of nesting).

**Comment by Naros** [comment]
Ah, now I understand.  

I believe that is a bit outside the purview of Orchestrator; however, I do think that is an excellent idea for another Godot plug-in that would provide you something like a visualization of a class hierarchy or class structure representation you often find in IDE tools.

**Comment by nullism** [comment]
Understood, thanks @Naros!
