### ISSUE TITLE
Instancing Scenes Not Working

### ISSUE THREAD

**Issue by TBNEO** [Vahera/godot-orchestrator#122]
### Describe the bug

Instancing scenes does not work, as trying to preload the packed scene as a resource doesn't seem to instantiate, nor is there any .instantiate() functionality

### Expected behavior

Expected to either have a way to instantiate scenes, or for them to be automatically instantiated on load/preload (see Preload Resource Node), and expected to be able to add scene node as a child of the current scene.

### Actual behavior

The result is the scene being preloaded as a resource, but isn't capable of being instantiated or spawned in any way, thus resulting in several errors when using Add Child with this as an input node to add.

### How to Reproduce?

1. Preload a scene in the graph
2. Connect to a Add Child node
3. Attempt to run project

### Godot full version

4.2

### Orchestrator version

2.0-dev3

### Additional information

My current theory for this is that it's being preloaded like any resource, but never instantiated, thus leading to unusability. This could be wrong though.

**Comment by Naros** [comment]
Hi @TBNEO, so I had thought that may work but looking at this more it won't for similar reasons to your theory.

What we'll do is add an `Instantiate Scene` node that will allow selecting the scene file and it will automatically instantiate it for you.  The returned object would be the scene's root `Node` that you can then use to call `add_child`, etc.
