### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by Slimey-dev** [Vahera/godot-orchestrator#128]
### Description

Hi, I would like to ask if there is any plans for orchestrator to support mobile platfroms like android or ios?

**Comment by Naros** [comment]
Hi @Slimey-dev, we actually would like to support mobile, we just need to introduce a Cmake build toolchain for it and then add a build step to the GitHub actions workflow so that we can construct an Android artifact that can be merged with the final plugin.

**Comment by Naros** [comment]
Hi @Slimey-dev et al, Orchestrator 2.1.dev1 and 2.0.1.stable both ship with Android support!.
If you run into any issues, please let us know.
