### ISSUE TITLE
Installed from Asset 3/4/24

### ISSUE THREAD

**Issue by swgmark** [Vahera/godot-orchestrator#138]
### Describe the bug

Is not enabled when i restarted after install
![Screenshot 2024-03-04 194253](https://github.com/Vahera/godot-orchestrator/assets/13492920/de412616-4884-44b2-bdc8-816e97b865f6)

### Expected behavior

It should enable on 2.4.1

### Actual behavior

Does not enable

### How to Reproduce?

4.2.1 Godot Asset Library, install from there

### Godot full version

v4.2.1.stable.mono.official [b09f793f5]

### Orchestrator version

Latest on Asset Store as of 3/4/24

**Comment by Naros** [comment]
Orchestrator v2 is not part of Godot's asset library yet as its still in pre-release.
Please down it from GitHub https://github.com/Vahera/godot-orchestrator/releases

**Comment by swgmark** [comment]
Really?

Even though your install instructions say the way is to obtain it from the asset store? [image.png]

Mark Kiessling
Ret USN
479 709 2333
***@***.***

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by swgmark** [comment]
That worked, maybe make a note on github so other do not get confused like i did. Looking forward to using it. Thanks for the Effort

Mark Kiessling
Ret USN
479 709 2333
***@***.***

The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.
