### ISSUE TITLE
handle mouse over

### ISSUE THREAD

**Issue by koncoweb** [Vahera/godot-orchestrator#148]
### Description

is there any graph node in orchestrator to handle mouse movements, i want to make FPS style camera

**Comment by Naros** [comment]
Hi @koncoweb, yes please take a look at the demo project.  There is a 3rd-person character and camera controller that can easily be retrofitted for FPS style if you need.  

If you have any further questions, please reach out on our discord as issues here are for enhancements or bug fixes.
