### ISSUE TITLE
Don't change icon on scene tree

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#152]
### Description

When adding a script to a node the icon in the scene tree change to Orchestrator icon. That will be very hard to work with when all the tree icon will have just one icon if many nodes have scripts. I can understand this is convenient when developing to see what nodes have it. But in production it will be a problem.

### Implementation ideas

Suggestion 1: Have a settings in UI that you can toggle on/off if you want to show the original icon of the node or the Orchestrator icon

Suggestion 2: Only show the original icon of the node type in the scene tree

**Comment by Naros** [comment]
Thanks for the reminder @GhostNr1.  I need to see specifically what is triggering this behavior because I agree. Ideally, it shouldn't be happening as we want Orchestrator to work just like GDScript, which does not do this.
