### ISSUE TITLE
able to resize the sidebar more

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#155]
### Description

When you are editing the nodes you want the area to be as large as possible. At the moment the two sidebars (left with all the files and right with function macros etc) take a lot of space. It would be good if we can resize them more.

### Implementation ideas

Just change so we can resize the sidebar more. Make the restriction a lot less so it up to be as a developer to decide how much of the information I want

**Comment by Naros** [comment]
Hi @GhostNr1, thanks for the feedback.

The Orchestrator file list can be collapsed using `Ctrl+\` or the `File > Toggle Orchestrator Panel` menu option.  This will hide the left file list and quickly allow you to open it as needed to gain valuable real estate.

You can also access the distraction-free mode in the Editor, toggled by this icon at the top-right of the main viewport area. The Editor provides this to collapse the left and right main editor dock panels as needed.
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/de6a9ff4-5fce-4c17-8245-166f8553e612)

If that isn't enough, you can also use the full-screen and multi-monitor pop-up toggle for Orchestrator, which can be found again at the top left of the main viewport next to the Orchestrator version.  This allows you to move the entire Orchestrator main view to another window separate from the Editor, work in split-screen between the Script/2D/3D viewports and the Orchestrator viewport, as well as maximize the Orchestrator window to your entire screen if needed.

![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/92fad42b-fb6e-4b9c-b5fa-41b0660e766e)

**Comment by GhostNr1** [comment]
Thanks for the response,

I guess the file list isn't that important that you need it up all the time. But the right one have a lot of space that is just wasted, in my impinge. If you check godos list you can do them kinda slim and they truncate the names and such.

I like to have the freedom to select how I want it rather then have restriction.
