### ISSUE TITLE
All Actions window not centered

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#176]
### Describe the bug

When the All Actions modal is open the top left corener is centered on the screen. So allways it is some outside of my screen and I have to move it to see everything at the bottom.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/efbacfcf-d617-411a-9f5e-9e2e300ecabf)

### Expected behavior

When open the window the center of the modal should be center of the screen

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc1.official [551ed1f73]

**Comment by Naros** [comment]
So I have this working, and I'm also going to add a new project setting so users can get the old behavior:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/7ffcab56-7474-4580-885d-cfed55700c1f)
