### ISSUE TITLE
Display if any function calls have a signal connected

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#183]
### Description

If you use GDScript and you connect a signal to a function you get a little green arrow next to it that indicate that this function is called from a signal. Clicking on it you get a list of all the signals that is connection to that function.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/fb9bb65f-bc9b-4845-ad74-32071824c77f)
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/55cb4e35-4ad0-41b0-8aad-a8df7159f78a)

### Implementation ideas

Have the same green arrow next to a function that has a signal connected to it. Be able to open the same window that display what is connected to this function.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/9dd0a61f-31ce-4e7b-b29d-1d059d607024)
I'm imagen it would be here somewhere

**Comment by Naros** [comment]
This took some work, but we finally have something that works like GDScript.  😁 

So first, in the Graphs component view, there will now be a new icon at the end of the name that indicates whether or not the graph is bound to a signal callback, as shown here:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/c89b570e-97bf-48b7-a478-f345e55cb1bb)

When clicking on the green icon, this opens a similar connections dialog window:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/f05ac5da-c80b-483b-8a43-08f7bb1552d5)

If you click on the scene tabs at the very top of the view and open a different scene that the script is not bound to, the graph component view updates, and the signal indicator icons will disappear:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/1d5fea13-e4ac-4246-9cd2-4372ce98b280)

When we detect the script is bound to a node in the current open scene, the indicators adjust accordingly.
