### ISSUE TITLE
Hi! Thank you for your positive feedback. We will look more into this and see what we can do.

### ISSUE THREAD

**Issue by 3ealityCreations** [Vahera/godot-orchestrator#184]
Hi! Thank you for your positive feedback. We will look more into this and see what we can do.

_Originally posted by @Zomphie in https://github.com/Vahera/godot-orchestrator/issues/110#issuecomment-1968849182_
            

NOTHING is freaking working, copying the "addon" folder into the project folder and it just copies the files it does not install or activate the plugin wtf??

**Comment by legbo** [comment]
Hello @3ealityCreations, create "addons" folder inside your project folder and then copy "orchestrator" plugin folder into it.

Path must look like: your_project_name_folder/addons/orchestrator

Then start your project and Godot will automatically detect plugin and after restart project, plugin will work properly without any advance setup.

**Comment by GhostNr1** [comment]
Go to the release section https://github.com/Vahera/godot-orchestrator/releases and find the latest release, the one in the top.
Download the one ending in plugin.zip. Not the demo projects.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/3a68b9d7-e6fe-4ff4-af39-d3e72664e744)
When the file is downloaded create a new project in Godot if you haven't done so. Open up the zip file in the root of your project. It should add an addon map with orchestrator in it.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/bff87424-454d-4b27-8035-44ec3def93d0)
If everything is done correct you should get a popup that ask you to reload Godot so it can load the new addon.
Next time you open up the project you should be able to use Orchestrator

**Comment by Naros** [comment]
Thanks @GhostNr1 and @legbo for your help, your information is correct ✅.  @3ealityCreations, if you continue to have any issues installing the plug-in, please visit our [discord](https://discord.com/invite/J3UWtzWSkT), and we'll be happy to help you more interactively.  If the steps provided above solve your problem, please _close_ this issue.  Thanks!

**Comment by Naros** [comment]
Closing as this issue has become stale.  If this continues to be a problem @3ealityCreations, please feel free to re-open.
