### ISSUE TITLE
When selecting a node have everything else dimmed

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#193]
### Description

Sometimes when you have a lot of connection and connection spanning far away it can be hard to see how things are connected. A suggestion is to ether have it so when you select a node everything else is dimmed and little transparent except for the box that is selected and all it's connection and lines from and to it. 

Like when you drag a new line it show only the boxes that you can interact with. But have all other boxes transparent so you can more clearly see it. Maybe have a switch to turn it on or off.

**Comment by Naros** [comment]
So while I don't mind adding this, I do find the behavior distracting, so I've made it configurable, with it off by default.  To enable the behavior, simply toggle it on in the `Project Settings > Orchestrator > UI` section:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/3a7c2814-3ef1-45a3-b0ce-9f6f3b6f428f)
