### ISSUE TITLE
When using "Highlight Selected Connections" all connections are highlighted and not just the one connect to the node

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#205]
### Describe the bug

When you select a node everything connected to that node should be highlighted to indicate what is connected. When I a node now all the nodes connected are correct but all the lines are also highlighted so it is very hard to see what is connected to this node. Only the nodes connected to this node should be highlighted and everything else should be dimmed down.
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/1ddee48b-56e7-42c9-93e8-94dfb026940f)
The pink lines for example should be dimmed down.

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc2

### Additional information

Instead of having this in the project settings would it be possible to chagne this to the toolbar for the graph so you can easy switch it on and off. 
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/5d1b3b70-3df8-435c-8be7-b1eeb0518580)

**Comment by Naros** [comment]
Ok, so I misunderstood the original request. I do think we can place it on the toolbar too, allowing for quick toggle access 👍
