### ISSUE TITLE
Show Message node speaker

### ISSUE THREAD

**Issue by Detusyl** [Vahera/godot-orchestrator#21]
### Describe the bug

The Show Message node uses the speaker variable instead of the speaker_name variable. It currently displays "Character" for the speakers name on every show message event. 

Changed line 49 to this: node.show_message(speaker_name, message, options)

### How to Reproduce?

Tried making a conversation between 2 people and realized everyone was named "Character".

### Godot full version

4.1

### Orchestrator version

1.0.5

**Comment by Zomphie** [comment]
Thank you for your report. We will look into this and apply a fix in the next build.

**Comment by Detusyl** [comment]
No problem, I also realized changing it to speaker_name makes the Narrator blank lol. Currently adding some conditions to it.
