### ISSUE TITLE
Missing Object.is_null

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#211]
### Describe the bug

At the moment there are Callable.is_null and Signal.is_null but the Object.is_null is missing

### Godot full version

4.2.1.stable

### Orchestrator version

v2.0.rc2

**Comment by Naros** [comment]
Hi @GhostNr1, Godot does not really expose anything like `Object::is_null`, but what they do provide is `is_instance_valid`:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/30b8bad8-4c66-4e79-af07-fe9a1cb94831)

Does this solve the issue?

**Comment by GhostNr1** [comment]
This is just reveresed but should solve this problem.
