### ISSUE TITLE
Include constants in search

### ISSUE THREAD

**Issue by GhostNr1** [Vahera/godot-orchestrator#222]
### Description

When you are searching for something that is a constant you don't get any result in what constant or if they are in a singletone. It would be good that you get some hint where stuff are. If you for example search for DisplayServer you should get a hint that this is in Engine Singleton. If you search for DisplayServer it show in the list Engine Singleton (DisplayServer). And if you select this it should automaticly select Engine Singleton and have DisplayServer selected in the list.

**Comment by Naros** [comment]
Applied to main (=2.1) and branch 2.0.
