### ISSUE TITLE
Change documentation engine from Antora to Docusaurus

### ISSUE THREAD

**Issue by VladimirLevadnij** [Vahera/godot-orchestrator#223]
### Description

Currently, the Antora engine is used to maintain documentation for Godot Orchestrator. As a result of using Antora, it turned out that some functionality was not implemented well enough, for example, the functionality of multilingual documentation together with version control.

As the respected @Zomphie reported, other engines are being considered for use, for example, Sphinx / Read the Docs which is used in the Godot project.

I recently started using the Docusaurus engine, I can say that it is a modern and powerful documentation engine. If there are plans to move away from using Antora, I suggest using Docusaurus 3.

@Zomphie said about this:

> We are looking at Docusaurus 3 and it does look very promising.
> If you want to play around with Docusaurus 3, you can. We will test this one out, it looks like it will provide us with the things we need.

### Implementation ideas

I can create a documentation project on Docusaurus 3 and transfer documentation from Antora to it, configure multilingual and version support in this engine.

**Comment by Zomphie** [comment]
Hi! To answer your question in discord, we will upload it.

**Comment by VladimirLevadnij** [comment]
Hello. Okay, thanks, I'm waiting for you to upload your local version of Docusaurus to the repository.

**Comment by Naros** [comment]
This has been implemented in the https://github.com/Vahera/godot-orchestrator-docs repository.  @Zomphie and @VladimirLevadnij, I think we can close this as complete, right?

**Comment by VladimirLevadnij** [comment]
@Naros Hello, yes, thanks for your proletarian shock work :-)
