### ISSUE TITLE
Addon does not initialize if downloaded from Asset Library

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#226]
### Describe the bug

Addon does not initialize if downloaded from Asset Library, Orchestrator tab is not visible even after editor restart

### Expected behavior

Orchestrator tab appearing after download from asset lib and editor restart

### Actual behavior

Orechestrator tab doesn't appear no matter how many times I restart in a fresh project

### How to Reproduce?

1. Create a new project
2. Download Orchestrator for Godot 4.2+ from the Asset Library
3. Manually restart the editor, no automatic promt appeared
4. Observe no orchestrator tab exists even after a restart
5. Also observe that Orchestrator is not put into "addons" folder in sits in res://orchestrator

### Godot full version

4.2.1.stable

### Orchestrator version

2.0.stable

### Additional information

Windows 11

**Comment by GhostNr1** [comment]
Can you try to see if it works if you follow this

1. Create a new project
2. In asset library press the download button.
3. When the install window is shown uncheck Ignore asset root <-- Very important
![image](https://github.com/Vahera/godot-orchestrator/assets/9337875/9550bdba-8a1d-49db-b99e-ed351fcd56d1)
4. Make sure the addons directory are shown under res:// when you do that.
5. Press the Install button
6. When installed a popup should come that ask to save and restart

**Comment by tarragonfly** [comment]
That solved it, thanks.

**Comment by Naros** [comment]
I've started a dialog with the Godot team to see if we can improve this process.  I'm going to close this for now, but do know its something we're going to try and improve somehow.
