### ISSUE TITLE
Warning when connecting signal via GUI

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#230]
### Describe the bug

When I connect a signal, this warnings appears in console: 

` D:\a\godot-orchestrator\godot-orchestrator\src\editor\graph\graph_edit.cpp:587 - _synchronize_graph_node cannot update existing nodes; likely a bug!?`

### Expected behavior

Console should be clean

### Actual behavior

There's a warning in console that might be a bug

### How to Reproduce?

1. Create a new project
2. Add Node2D to the scene
3. Create new orchestration
4. Add orchestration on the Node2D
5. From Node/Signals GUI connect any signal from previously added Node2D to the orchestration that's attached to it

### Godot full version

v4.2.1.stable

### Orchestrator version

2.0.stable

### Additional information

The signals do work as intended as far as I can tell.

**Comment by Naros** [comment]
Applied to main (=2.1) and branch 2.0.
