### ISSUE TITLE
Godot crashing when adding function on orchestrator visual script

### ISSUE THREAD

**Issue by FakeDivinity** [Vahera/godot-orchestrator#236]
### Describe the bug

When i try adding any function on the .os, it just load and crushes. Please help

### Godot full version

Godot 4.2.1 stable

### Orchestrator version

2.0.0

**Comment by GhostNr1** [comment]
What operative system do you use?
Do you add them via enter or click the add button? Have you tried both?

**Comment by Naros** [comment]
It would be helpful if you could (a) share the steps you've taken to create function and (b) if you can attach the `.os` file here, we can certainly take a look at the data and see if there is something that got corrupted @FakeDivinity; thanks.

**Comment by FakeDivinity** [comment]
Sorry for the late reply, I'm using windows 11 operating system.
This what happens when I try to add a function:

https://github.com/Vahera/godot-orchestrator/assets/103278415/9dbb6d7b-0216-4f90-9154-23ffd5d57cf7

**Comment by FakeDivinity** [comment]
> It would be helpful if you could (a) share the steps you've taken to create function and (b) if you can attach the `.os` file here, we can certainly take a look at the data and see if there is something that got corrupted @FakeDivinity; thanks.
