### ISSUE TITLE
Cannot remove actions from favorites without going in project settings

### ISSUE THREAD

**Issue by RadiantUwU** [Vahera/godot-orchestrator#307]
### Describe the bug

Accidentally favoriting something has no clear way to remove it from favorites without having to go to ProjectSettings.

### Expected behavior

If you want to remove something from favorites, you would usually go check for something like a full star to click it to go back to favorites, right?
![image](https://github.com/Vahera/godot-orchestrator/assets/69520693/948890a9-b879-4bde-b021-84f8e5c3930a)

### Actual behavior

There isnt a star to be able to remove it back from favorites, forcing you to go in project settings.

### Orchestrator version

v2.0

**Comment by Naros** [comment]
Hi @RadiantUwU, this should definitely be clearer.  As a workaround, if you search for the item and re-click the full :star: then it will unfavorite.  This will be much clearer in the new redesigned **All Actions** dialog coming in the next update which uses this style:

![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/47a4461f-d578-4553-be98-5d54b2471cab)
