### ISSUE TITLE
ScriptExtension::_get_language missing

### ISSUE THREAD

**Issue by RadiantUwU** [Vahera/godot-orchestrator#308]
### Describe the bug

```
E 0:00:01:0615   _gdvirtual__get_language_call: Required virtual method ScriptExtension::_get_language must be overridden before calling.
  <C++ Source>   ./core/object/script_language_extension.h:133 @ _gdvirtual__get_language_call()
```

### How to Reproduce?

Change test locale in internationalization in Project Settings

### Godot full version

v4.3.dev5.official [c9c17d6ca]

### Orchestrator version

v2.0

**Comment by Naros** [comment]
Fixed by this upstream PR https://github.com/godotengine/godot/pull/90776 as its a Godot bug.
