### ISSUE TITLE
Deleting a script before detaching it causes major issues

### ISSUE THREAD

**Issue by RadiantUwU** [Vahera/godot-orchestrator#310]
### Describe the bug

![image](https://github.com/Vahera/godot-orchestrator/assets/69520693/4372aaad-b277-4e60-a07b-6064e62add85)

### Expected behavior

N/A

### Actual behavior

Failing to save the scene.

### How to Reproduce?

1. Attach script by orchestrator
2. Save scene
3. Reload project
4. Delete the script
> ![image](https://github.com/Vahera/godot-orchestrator/assets/69520693/aba60586-fccc-4d0d-a931-b1057612921a)
5. Detach and try to save scene.

### Godot full version

v4.3.dev5.official [c9c17d6ca]

### Orchestrator version

v2.0

**Comment by Naros** [comment]
Hi @RadiantUwU was the script still loaded in the Orchestrator main view when you deleted it?
