### ISSUE TITLE
Add support for `Image`, `ClassDB`

### ISSUE THREAD

**Issue by RadiantUwU** [Vahera/godot-orchestrator#316]
### Description

Add support for methods.

**Comment by Naros** [comment]
Access for `Image` should be available in 2.1.dev1 and will be in 2.0.1.stable using the `New Instance` feature introduced in the PR changes for https://github.com/Vahera/godot-orchestrator/issues/265.  

As for `ClassDB`, this is available using the `Engine Singleton` node already in 2.0.stable
