### ISSUE TITLE
Dictionary.get returns nothing

### ISSUE THREAD

**Issue by RadiantUwU** [Vahera/godot-orchestrator#317]
### Describe the bug

![image](https://github.com/Vahera/godot-orchestrator/assets/69520693/8bc5d1c9-8cf5-45c6-9869-549db97d064d)

### Godot full version

v4.3.dev5.official [c9c17d6ca]

### Orchestrator version

v2.0

**Comment by RadiantUwU** [comment]
Added to this bug report, calling a callable returns nothing

**Comment by Naros** [comment]
These have all been fixed in https://github.com/Vahera/godot-orchestrator/issues/289
