### ISSUE TITLE
Crashed on New Orchestration

### ISSUE THREAD

**Issue by Deadhyena** [Vahera/godot-orchestrator#335]
### Describe the bug

Godot keeps crashing when creating a new orchestration, no matter if it's a new file or an existing one.

### How to Reproduce?

1. Donwload&Install Orchestrator via Asset Library
2. >New Orchestration

### Godot full version

4.2.2 stable

### Orchestrator version

2.0.1 Stable

**Comment by Naros** [comment]
What operating system are you using and is the Godot 4.2.2.stable version the official build @Deadhyena ?

**Comment by Deadhyena** [comment]
@Naros Windows 11 23H2, Godot 4.2.2 via Steam
Yes, you are right, but I have tried on both 2.0.0 and 2.1 dev with the same result

**Comment by Naros** [comment]
Please use the official build from Godot, the Steam build is not compatible with GDExtension libraries.

**Comment by Deadhyena** [comment]
_Did you make sure when you installed the plugin from the asset library that you unchecked the Ignore asset root checkbox?_
Yes, that's exactly what I did. 

I just opened my projects (with installed Orchestrator) using the non-Steam version of Godot and everything works fine, however Steam version refuses to work with Orchestrator even after reinstallation.

**Comment by Naros** [comment]
When it crashes, is there anything logged in the Windows **Event Viewer** under the `Windows Logs` section in either the "Application", "Security", or "System" categories that relates to the crash?  If so, if you could share those detail here that would be most helpful.

**Comment by Deadhyena** [comment]
@Naros here are test results, I hope that helps.
![report_1](https://github.com/Vahera/godot-orchestrator/assets/142090767/ed0db634-ea10-4f21-9a56-fc517e2fdbf3)
![report_2](https://github.com/Vahera/godot-orchestrator/assets/142090767/3029d341-26bc-4343-a33f-6f9ad8eee7f0)
![report_3](https://github.com/Vahera/godot-orchestrator/assets/142090767/e0e8daac-175d-4955-8b55-58cc52959f64)

[Crash_log.zip](https://github.com/Vahera/godot-orchestrator/files/15224648/Crash_log.zip)

**Comment by Deadhyena** [comment]
For anyone who has the same issue but wants to stay on the Steam platform for example to keep track of time, I found a weird workaround. 

1. Download Godot from official website
2. Open Godot local folder in Steam (Steam\steamapps\common\Godot Engine)
3. Rename your downloaded Godot .exe (godot.windows.opt.tools.64.exe) 
4. Replace .exe in Steam folder with a new one. If you've downloaded the mono version - drop GodotSharp folder into Steam folder too

Orchestrator is working alright now.
