### ISSUE TITLE
gdvirtual get language cal: Required virtual method ScriptExtension. .get language must be overridden before caling.

### ISSUE THREAD

**Issue by TrifingZW** [Vahera/godot-orchestrator#358]
### Describe the bug

In godot 4.2.2, an error is reported every time it is run: ./core/object/script language extension.h:120 @ _gdvirtual get language_call()
Error: gdvirtual get language cal: Required virtual method ScriptExtension. .get language must be overridden before calling. 
Although it doesn’t cause any problems, it’s really annoying to get the error every time.
![QQ截图20240514204616](https://github.com/Vahera/godot-orchestrator/assets/67575386/4ae2e51c-1d32-4439-86f6-c7b5ae9841c3)

### Godot full version

v4.2.2.stable.mono.official

### Orchestrator version

v2.0.1，v2.1.dev2

**Comment by Naros** [comment]
This is a Godot upstream bug -- https://github.com/godotengine/godot/issues/80275.
This was fixed in Godot 4.3, see - https://github.com/godotengine/godot/pull/90776.
