### ISSUE TITLE
Orchestrator crashes when using the godot-minimal-theme

### ISSUE THREAD

**Issue by Naros** [Vahera/godot-orchestrator#390]
### Describe the bug

When installing the `godot-minimal-theme` as a custom theme in Godot, the editor crashes. This is because Orchestrator makes a few assumptions about the types of `StyleBox` implementations that are part of the base Godot editor.  This theme specifically changes the style of `ItemList` from a `StyleBoxFlat` to a `StyleBox`, and our implementation attempted to adjust some corner radiuses which cannot be applied to basic `StyleBox` types.

### Expected behavior

Editor shouldn't crash.

### Godot full version

4.2.2-stable

### Orchestrator version

2.1.dev2

**Comment by neilfranci** [comment]
Did you test with the 1.5.0 https://github.com/passivestar/godot-minimal-theme 
with the current 2.1 dev3 Orchestrator? Because, whenever I use the theme it just keeps crashing when creating or open .os
godot 4.3.beta2

![image](https://github.com/Vahera/godot-orchestrator/assets/66520542/382abc06-d580-4743-93a9-413a422cf9fd)

**Comment by Naros** [comment]
Hi @neilfranci, thanks for the feedback.

No, we did not primarily because we do not yet officially support Godot 4.3 as there were some API changes in the code interfaces between Godot 4.2 and 4.3 at the GDExtension level and in some of the Godot widgets we use.  While a stock Godot 4.3 environment may work with Orchestrator, it's not yet tested and may result in crashes due to API changes.

We'll take a look and add a fix if godot-minimal-theme fails on Godot 4.3 and Orchestrator 2.1 for the dev4 build where we intend to officially support Godot 4.3.
