### ISSUE TITLE
This asset is gona get updated for the godot version 4.2?

### ISSUE THREAD

**Issue by KickCreator** [Vahera/godot-orchestrator#42]
### Description

I tried to import this asset in the new version of Godot 4.2 but it has many errors. Is there a way to fix them? Will they release a patched version for Godot 4.2?

Line code errors:

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:15 - Parse Error: Identifier "show_close" not declared in the current scope.

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:20 - Parse Error: Identifier "close_request" not declared in the current scope.

res://addons/orchestrator/core/orchestration_node.gd:-1 - Compile Error:

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:15 - Parse Error: Identifier "show_close" not declared in the current scope.

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:20 - Parse Error: Identifier "close_request" not declared in the current scope.

res://addons/orchestrator/components/editor/orchestration_graph.gd:-1 - Compile Error:

modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/orchestrator/components/editor/orchestration_graph.gd" with error "Compilation failed". (User)

**Comment by Naros** [comment]
Hi @KickCreator if you restart Godot 4.2 after installing the plugin and enabling, do you still get these errors?

**Comment by KickCreator** [comment]
Ok I tried that and it seems that it fixes most of the initial problems but
some of them keep appearing
[image: Captura.JPG]

**Comment by Naros** [comment]
Hi @KickCreator the image wasn't sent via email, can you attach the image here so we can see what is the problem?

**Comment by KickCreator** [comment]
Sure, here it is.

Also, I will writhe the line errors here (in case that the image doesn't
work)

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:15
- Parse Error: Identifier "show_close" not declared in the current scope.

res://addons/orchestrator/components/editor/orchestration_graph_node.gd:20
- Parse Error: Identifier "close_request" not declared in the current scope.

res://addons/orchestrator/components/editor/orchestration_graph.gd:-1 -
Compile Error:

modules/gdscript/gdscript.cpp:2775 - Failed to load script
"res://addons/orchestrator/components/editor/orchestration_graph.gd" with
error "Compilation failed". (User)

**Comment by Naros** [comment]
Just merged GH-22 to address the 4.2 compatibility @KickCreator, we'll be cutting a release shortly.

**Comment by KickCreator** [comment]
Thanks, I'll check it out!
