### ISSUE TITLE
Move Orchestrator to GDExtension

### ISSUE THREAD

**Issue by Naros** [Vahera/godot-orchestrator#43]
### Description

The Godot GDExtension framework, offered by their `godot-cpp` project, provides access to a variety of engine features that are not all directly available using GDScript.  It also provides a C++-based runtime that can be more efficient for implementing scripting languages than embedding one language within another as we did with Orchestrator v1.

**Comment by Naros** [comment]
@gvrocksnow, with the move to GDExtension we are planning to move to Apache License 2.0 rather than MIT.  While the code will be entirely different in C++ rather than GDScript, just wanted to confirm if you consent to this license change.

**Comment by gvrocksnow** [comment]
@Naros That's fine with me

**Comment by Naros** [comment]
Merged #44, `main` now is based on Orchestrator 2
