### ISSUE TITLE
Orchestrator doesn't work on 4.3-beta2 (yet)

### ISSUE THREAD

**Issue by fire** [Vahera/godot-orchestrator#446]
### Describe the bug

Orchestrator doesn't work on 4.3-beta2 (yet)

### Expected behavior

Clicking on orchestrator and opening a .os file will allow me to edit it.

### Actual behavior

Clicking on orchestra tor and opening a .os file will crash.

### How to Reproduce?

1. download godot 4.3-beta2 from godot engine org
2. Install orchestrator (I tried upgrading the godot-cpp and it was failing.

### Godot full version

4.3-beta2 (b75f0485ba15951b87f1d9a2d8dd0fcd55e178e4)

### Orchestrator version

614a6f2cde0676aa59607c5afd1fd184fc41f814

### Additional information

My friend was trying to use Orchestrator on 4.3-betas and wasn't able to.

See also: https://github.com/Vahera/godot-orchestrator/pull/422

**Comment by fire** [comment]
Worked on this a little https://github.com/V-Sekai-fire/godot-orchestrator/tree/4.3-beta2

**Comment by Naros** [comment]
Unfortunately the latest godot-cpp 4.3-beta2 introduced a `CRASH_NOW` macro, and this is probably what your friend saw.  

The issue with this change is that it breaks backward compatibility but, moreover, breaks the expectation that working in a C++ module should be nearly identical to GDExtension.  The fact you can no longer define a Godot object on the stack in GDE but you can in the engine seems unintended.

**Comment by Naros** [comment]
This should be fixed on `main` now.
