### ISSUE TITLE
AssetLib version imports unnecessary files

### ISSUE THREAD

**Issue by KAW0** [Vahera/godot-orchestrator#45]
### Describe the bug

Importing this library from asset lib will put 
.github
CHANGELOG.md
LICENSE
README.md
files and docs directory into main project directory while those stuff should all land in addons/orchestrator

**Comment by Zomphie** [comment]
Hi! Thank you for your report. Please tell me if you have the option to omit these extra files from your files when you download them from the asset library. I believe you have an option to omit these files.

**Comment by Naros** [comment]
Thanks for the report @KAW0, I've fixed this in `main`.
