### ISSUE TITLE
Demo broken dependenciss

### ISSUE THREAD

**Issue by Gallilus** [Vahera/godot-orchestrator#64]
### Describe the bug

![image](https://github.com/Vahera/godot-orchestrator/assets/20573784/1e0ad74b-2575-4573-8529-3fdfa5571870)

### Expected behavior

Startup without errors

### Actual behavior

see image above

### How to Reproduce?

Open `godot-orchestrator-demo-v2.0-dev1-win32`
Using Godot 4.2 stable on Windows 10

### Godot full version

Godot 4.2 stable

### Orchestrator version

v2.0-dev1-win32

**Comment by Naros** [comment]
Do you see an `Orchestrator` button on the top navigation panel?  This typically happens if the editor was not restarted or when the plugin was not loaded by the Editor @Gallilus .

**Comment by Naros** [comment]
> Nope after restarting Godot I get the same message and there is no Orchestrator tab.

Are you using Godot 4.2.0-stable or 4.2.1-stable?  If you have 4.2.0-stable, could you try with 4.2.1-stable.

**Comment by Gallilus** [comment]
Jep. That is the one! I quickly tried `compatibility_minimum="4.2.1"` but it gives no warning.

**Comment by Naros** [comment]
> Jep. That is the one! I quickly tried `compatibility_minimum="4.2.1"` but it gives no warning.

When you say it gives no warning, are you getting the "Orchestrator" tab at the top of the Editor?

**Comment by Naros** [comment]
So I can confirm, if I open the project with the 4.2-stable editor, I get these errors:
```
 D:\a\godot-orchestrator\godot-orchestrator\extern\godot-cpp\src\godot.cpp:283 - Cannot load a GDExtension built for Godot 4.2.1 using an older version of Godot (4.2.0).
  core/extension/gdextension.cpp:748 - GDExtension initialization function 'extension_library_init' returned an error.
  Failed loading resource: res://addons/orchestrator/orchestrator.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```
Using Godot Editor 4.2.1-stable works.
