### ISSUE TITLE
Crash on extending bool socket from branch node (4.2.1 mono 2.0 dev 2 ) 

### ISSUE THREAD

**Issue by TheBricktop** [Vahera/godot-orchestrator#82]
### Describe the bug

While clicking on a bool socket on branch node and then clicking to create a node to connect it to im experiencing a crash to desktop. Branch node is connected to physic process event node.

### Expected behavior

Creates a new node and doesnt crash

### Actual behavior

Crashes to desktop

### How to Reproduce?

1. Create fresh empty project in Godot 421 mono
2. create a new node 3d 
3. add new script 
4. create processing event  node
5. connect it to new branch node
6. extend bool socket to create new node 
7. crash ensues 

### Godot full version

4.2.1 Mono

### Orchestrator version

2.0 dev 2

**Comment by Naros** [comment]
As a work around, can you try creating the node that you want to connect to the `bool` port manually and then connect from the newly placed node to the branch's `bool` port, does that work @TheBricktop ?

**Comment by Naros** [comment]
I've attached a build based on the linked PR. Could you replace the contents of your project's `addons\orchestrator` folder with the contents of the attached plugin bundle and let me know if it solves your problem @TheBricktop?  

[godot-orchestrator-v2.0-dev2-plugin-windows-fix.zip](https://github.com/Vahera/godot-orchestrator/files/14044155/godot-orchestrator-v2.0-dev2-plugin-windows-fix.zip)
[godot-orchestrator-v2.0-dev2-plugin-macos-fix.zip](https://github.com/Vahera/godot-orchestrator/files/14044156/godot-orchestrator-v2.0-dev2-plugin-macos-fix.zip)
[godot-orchestrator-v2.0-dev2-plugin-linux-fix.zip](https://github.com/Vahera/godot-orchestrator/files/14044159/godot-orchestrator-v2.0-dev2-plugin-linux-fix.zip)

**Comment by TheBricktop** [comment]
That fixed it thank You!
