### ISSUE TITLE
Input.get_vector is missing

### ISSUE THREAD

**Issue by TheBricktop** [Vahera/godot-orchestrator#84]
### Description

Currently im trying to make simple character controller, and I tried to find Input.get_vector as it is a nice shortcut for common keybinding setup and I cant seem to find it through new node menu.

### Implementation ideas

I can of course program my own node or function but native implementation would be nice.

![image](https://github.com/Vahera/godot-orchestrator/assets/3866030/9f72e757-a8f0-45f4-a98e-4c539d91d76f)

**Comment by Naros** [comment]
Hi @TheBricktop, so to access that specific function on the `Input` singleton, you will need to drop an Engine Singleton node and set the singleton to `Input`.  From there, dragging from that to the canvas will provide you all the APIs on the `Input` singleton, as shown here in our demo `player.os` character controller:

![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/beb5855c-7c20-4600-81ae-0f16781b6b1a)

**Comment by TheBricktop** [comment]
Thank You, that clarifies this.
But there is some issue with clarity of the "All Actions" menu, for example my issue is that when I extend the socket with defined type id like to see in the list of possible nodes the relevant nodes that have a socket of the type or accept the type that im extending from, and with above example when I type "Input"  in the finder im only getting "input action" and no suggestion on Input singleton.
And also common flow nodes like branch should appear on top of the list because even when I type "branch" im scrolling the list to the bottom, this can be easily fixed now with a dedicated shortcut (maybe there is one but I didnt stumble upon it).
![image](https://github.com/Vahera/godot-orchestrator/assets/3866030/4d1cb687-6373-4e77-bd6b-1a10739b49d0)

**Comment by Naros** [comment]
> But there is some issue with clarity of the "All Actions" menu, for example my issue is that when I extend the socket with defined type id like to see in the list of possible nodes the relevant nodes that have a socket of the type or accept the type that im extending from, and with above example when I type "Input" in the finder im only getting "input action" and no suggestion on Input singleton.

So if you are dragging a connection from the Input singleton, the "All Actions" menu will work this way.  By default if you are not providing any context by dragging from an existing pin, then the all actions dialog bases the default list based on the base type of the Orchestration.  If you have any suggestions on how to change this behavior, I'm certainly open to entertain that.

> And also common flow nodes like branch should appear on top of the list because even when I type "branch" im scrolling the list to the bottom, this can be easily fixed now with a dedicated shortcut (maybe there is one but I didnt stumble upon it).

What would you think about introducing the ability to click a ⭐ on the right side of an action to indicate it is a favorite and those would always be listed at the top of the dialog?

**Comment by TheBricktop** [comment]
That would certainly be an enchancement.

**Comment by Naros** [comment]
Hi @TheBricktop, so this is what I have designed thus far; the design is still open to discussion.

The action menu now contains a button on the right end of the `TreeItem` as a ⭐ that can be clicked:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/2080d58f-5f87-447e-9d77-e623970ddaf8)

When the ⭐ is clicked, it becomes filled in to indicate that it is a `Favorite` and a new `Favorites` section is prepended at the top of the action list, as shown here:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/3073171c-bb6e-4c1d-b7b0-7c63688c285e)

The `Favorites` sub-section is only visible when at least one action has been flagged as a favorite.  These are stored at the project level in the project file, so you don't need to specify these per orchestration or anything like that.

In addition, when you begin to type in a keyword in the filter text box, the actions menu will begin pre-selecting the first leaf node that matches the filtered keyword criteria, as shown here:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/e99529e2-2599-4918-afe3-044120421175)

This allows users to use the `Enter` key if the selected item is the desired node to quickly add it to the graph canvas.

What do you think?  Have I missed anything that could be useful?
