### ISSUE TITLE
Consider removing fuzzy finder animation 

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#90]
### Description

One thing that immediately frustrates me when starting to use the v2 version of the tool is the fuzzy finder popup with a fancy animation that's 0.5f-1f long. It disrupts my flow and slows me down. I'd much prefer if it appeared as fast as possible.

**Comment by Naros** [comment]
Hi @tarragonfly, could you show a screen shot of the animation and fuzzy finder you're referring to?

**Comment by tarragonfly** [comment]
> Hi @tarragonfly, are you referring to the focus node behavior? If so, sure, I don't see why we couldn't add an option to disable the animation if it's problematic or inhibits the workflow.

No, I'm talking about node search fade in/scale up. 

![example](https://i.imgur.com/iNg5Ts7.gif)

**Comment by Naros** [comment]
> No, I'm talking about node search fade in/scale up.

I'll take a look but AFAIK that is standard Godot.  If you open any of Godot's standard pop-out dialogs like Project Settings, Editor Settings, and even the About Dialog, they all work this way.

**Comment by Naros** [comment]
Hi @tarragonfly so this is actually not controlled by Godot but is instead controlled by the Operating System.

On Windows 11, Open `Settings > Accessibility > Visual Effects` and disable the **Animation Effects**:
![image](https://github.com/Vahera/godot-orchestrator/assets/3255568/85355dff-28d8-4c24-a6c8-347a96ec4ca8)

If you're using another Operating System, please refer to their documentation to see how to disable these effects.
