### ISSUE TITLE
Error in console: ScriptExtension::_gdvirtual__get_language_call

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#95]
### Describe the bug

E 0:00:00:0621   ScriptExtension::_gdvirtual__get_language_call: Required virtual method ScriptExtension::_get_language must be overridden before calling.
  <C++ Source>   .\core/object/script_language_extension.h:120 @ ScriptExtension::_gdvirtual__get_language_call()

### Expected behavior

Clean console

### Actual behavior

Console is not clean

### How to Reproduce?

1. Create new orchestration.
3. Drag the orchestration on some scene node. (My Hierarchy is Node2D/CanvasLayer. Orchestration is on CanvasLayer)
4. Enter Play mode
5. Notice the error in console

### Godot full version

4.2.1

### Orchestrator version

2.0.dev2

**Comment by Naros** [comment]
This is a Godot upstream bug -- https://github.com/godotengine/godot/issues/80275

**Comment by Colassal** [comment]
Getting this error on my end as well - I know it is an upstream godot issue, but are there any known workarounds/bandaids I can do on my end to make Orchestrator work? I ask because I really wanted to try this out to handle some of the more complex to understand code I have visually, but as is I can't get it to work at all.

**Comment by Naros** [comment]
> Getting this error on my end as well - I know it is an upstream godot issue, but are there any known workarounds/bandaids I can do on my end to make Orchestrator work? I ask because I really wanted to try this out to handle some of the more complex to understand code I have visually, but as is I can't get it to work at all.

Hi @Colassal, this does not impact Orchestrator, it's just an annoying error  👍

**Comment by Colassal** [comment]
> > Getting this error on my end as well - I know it is an upstream godot issue, but are there any known workarounds/bandaids I can do on my end to make Orchestrator work? I ask because I really wanted to try this out to handle some of the more complex to understand code I have visually, but as is I can't get it to work at all.
> 
> Hi @Colassal, this does not impact Orchestrator, it's just an annoying error 👍 If you can't get it to work, then let us know what's going on because this only impacts the editor debugger, which Orchestrator cannot access since its not exposed via GDExtension at this time.

Hey,

Thanks for the quick response! I see now it isn't that error that is causing it, it is just the only exposed error I can get. I will open a new issue for what is going on.

**Comment by Naros** [comment]
Fixed in Godot 4.3.dev6, https://github.com/godotengine/godot/pull/90776.
