### ISSUE TITLE
Crash on trying to connect PackedArray variable to Array Pick Random node

### ISSUE THREAD

**Issue by tarragonfly** [Vahera/godot-orchestrator#97]
### Describe the bug

Editor crash when trying to connect PackedArray variable to Array Pick Random node

### Expected behavior

Anything but editor crash

### Actual behavior

Editor crashes

### How to Reproduce?

1. Create new variable of type PackedInt32Array
2. Add Array/Pick Random node to an EventGraph
3. Drag PackedInt32Array variable in EventGraph to get the Getter node
4. Try to connect PackedArray variable node's value output to Pick Random node's input
5. Notice the editor crash

### Godot full version

4.2.1

### Orchestrator version

2.0.dev2

**Comment by Naros** [comment]
Hi @tarragonfly, again can you confirm whether you're using the binary from #82 ?  
If not, could you grab that binary and see whether that solves the crash problem.

**Comment by tarragonfly** [comment]
> Hi @tarragonfly, again can you confirm whether you're using the binary from #82 ? If not, could you grab that binary and see whether that solves the crash problem.

Indeed, the linked binary also addresses this issue.

**Comment by Naros** [comment]
Great, I'll go ahead and close this, and the fix will be in dev3, likely sometime this weekend.
