### ISSUE TITLE
Orchestrator icon next to the tab title

### ISSUE THREAD

**Issue by elenakrittik** [Vahera/godot-orchestrator#98]
### Description

"2D", "3D", "Script", etc. all have an icon on the left, so it would be nice if Orchestrator had one as well.

![image](https://github.com/Vahera/godot-orchestrator/assets/77104725/7f88d978-1c1e-4d1b-b3dc-ada1d919f801)

### Implementation ideas

I see there is an SVG of Orchestrator's logo in addon zips downloaded from Releases, so it can (probably?) just be recolored to white to get a version that'll fit into the rest of the editor. It'll also probably need to [be scaled](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#a-custom-node) (see bottom note) appropriately. To set up an icon in GDScript you'll need to override `EditorPlugin._get_plugin_icon()`; in C++, it seems like you should override `EditorPlugin.get_icon()` instead, see [here](https://github.com/godotengine/godot/blob/master/editor/editor_plugin.cpp#L309-L312).

**Comment by Naros** [comment]
Hi @elenakrittik, we actually do implement the `_get_plugin_icon()` method, found [here](https://github.com/Vahera/godot-orchestrator/blob/main/src/plugin/plugin.cpp#L125-L128) .

The main issue is that the icons need to be imported before Godot can render them and there is a race condition with the GDExtension framework where the editor plugin loads the icon before the importers have been registered, which creates this problem.  Once the plug-in has been loaded and the icon imports created, if you restart the editor one last time, you'll notice an icon there like the other tabs.

I'll double-check with the Godot team and see whether there is a workaround.
